export class Contracts{
    constructor(
        public _id : string="",
        public contractname:string="",
        public tokenname : string="",
        public tokensymbol: string="",
        public decimals : string="",
        public tokentype : string="",
        public tokenowner : string="",
        public invstad : string="",      
        public tokenrate : string="",
        public hardcaptokens : string="",
        public softcaptokens : string="",
        public startdate : string="",
        public starttime : string="",
        public whitelist : string="",
        public changingdates : string="",
        public transferable : string="",
        public invlimit: string="",
        public minlimit: string="",
        public maxlimit: string="",
        public bonus1 : string="",
        public bonus2 : string="",
        public bonus3 : string="",
        public bonus4 : string="",
        public bonus5 : string="",
        public bonus6 : string="",
        public bonus7 : string="",
        public bonus8 : string="",
        public bonus9 : string="",
        public amountbonus1: string="",
        public amountbonus2: string="",
        public amountbonus3: string="",
    ){}
}
