var mongoose = require('mongoose');
var ContractsSchema = new mongoose.Schema({
    contractname:String,
    tokensymbol:String,
    tokenname:String,
    decimals:String,
    tokentype:String,
    invstad:String,
    tokenrate:String,
    tokenowner:String,
    tokenrate:String,
    hardcaptokens:String,
    softcaptokens:String,
    startdate:String,
    starttime:String,
    whitelist:String,
    changingdates:String,
    transferable:String,
    invlimit:String,
    minlimit:String,
    maxlimit:String,
    bonus1:String,
    bonus2:String,
    bonus3:String,
    bonus4:String,
    bonus5:String,
    bonus6:String,
    bonus7:String,
    bonus8:String,
    bonus9:String,
    amountbonus1:String,
    amountbonus2:String,
    amountbonus3:String
});
module.exports = mongoose.model('Contracts', ContractsSchema);